# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'

from PyQt5 import QtGui, QtCore, uic, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.QtCore import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.evaluationBox = QtWidgets.QGroupBox(self.centralwidget)
        self.evaluationBox.setGeometry(QtCore.QRect(600, 100, 401, 141))
        self.evaluationBox.setTitle(_fromUtf8(""))
        self.evaluationBox.setObjectName(_fromUtf8("evaluationBox"))
        self.label_3 = QtWidgets.QLabel(self.evaluationBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 371, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit = QtWidgets.QLineEdit(self.evaluationBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.parse = QtWidgets.QPushButton(self.evaluationBox)
        self.parse.setGeometry(QtCore.QRect(270, 90, 121, 41))
        self.parse.setObjectName(_fromUtf8("parse"))
        self.rowWithButtons = QtWidgets.QGroupBox(self.centralwidget)
        self.rowWithButtons.setGeometry(QtCore.QRect(20, 300, 140, 350))  # Widget which has all buttons in it
        self.rowWithButtons.setTitle(_fromUtf8(""))
        self.rowWithButtons.setObjectName(_fromUtf8("rowWithButtons"))
        self.displayButton = QtWidgets.QPushButton(self.rowWithButtons)
        self.displayButton.setGeometry(QtCore.QRect(10, 10, 110, 30))
        self.displayButton.setObjectName(_fromUtf8("displayButton"))
        self.firstButton = QtWidgets.QPushButton(self.rowWithButtons)
        self.firstButton.setGeometry(QtCore.QRect(10, 75, 110, 30))
        self.firstButton.setObjectName(_fromUtf8("firstButton"))
        self.lr1Button = QtWidgets.QPushButton(self.rowWithButtons)
        self.lr1Button.setGeometry(QtCore.QRect(10, 150, 110, 30))
        self.lr1Button.setObjectName(_fromUtf8("lr1Button"))
        self.lalrButton = QtWidgets.QPushButton(self.rowWithButtons)
        self.lalrButton.setGeometry(QtCore.QRect(10, 225, 110, 30))
        self.lalrButton.setObjectName(_fromUtf8("lalrButton"))
        self.parseTableButton = QtWidgets.QPushButton(self.rowWithButtons)
        self.parseTableButton.setGeometry(QtCore.QRect(10, 300, 111, 31))
        self.parseTableButton.setObjectName(_fromUtf8("parseTableButton"))
        self.displayScreen = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayScreen.setGeometry(QtCore.QRect(200, 300, 800, 350))  # Screen for displaying
        font = QtGui.QFont()
        font.setPointSize(12)
        self.displayScreen.setFont(font)
        self.displayScreen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayScreen.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.displayScreen.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.displayScreen.setObjectName(_fromUtf8("displayScreen"))
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(23, 80, 550, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        #sizePolicy.setHorizontalStretch(0)
        #sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.epsilonBox = QtWidgets.QGroupBox(self.centralwidget)
        self.epsilonBox.setGeometry(QtCore.QRect(900, 60, 101, 31))
        self.epsilonBox.setTitle(_fromUtf8(""))
        self.epsilonBox.setObjectName(_fromUtf8("epsilonBox"))
        self.label_4 = QtWidgets.QLabel(self.epsilonBox)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName(_fromUtf8("actionAuthor"))
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_About.addAction(self.actionAuthor)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.label_3.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.plainTextEdit)

        self.displayUIElements(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plainTextEdit, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.parse)
        MainWindow.setTabOrder(self.parse, self.displayButton)
        MainWindow.setTabOrder(self.displayButton, self.firstButton)
        MainWindow.setTabOrder(self.firstButton, self.lr1Button)
        MainWindow.setTabOrder(self.lr1Button, self.lalrButton)
        MainWindow.setTabOrder(self.lalrButton, self.parseTableButton)
        MainWindow.setTabOrder(self.parseTableButton, self.displayScreen)

    def displayUIElements(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_3.setText(_translate("MainWindow", "Enter expression to evaluate :", None))
        self.parse.setText(_translate("MainWindow", "Parse", None))
        self.displayButton.setText(_translate("MainWindow", "Display", None))
        self.firstButton.setText(_translate("MainWindow", "First", None))
        self.lr1Button.setText(_translate("MainWindow", "LR(1) items", None))
        self.lalrButton.setText(_translate("MainWindow", "LALR items", None))
        self.parseTableButton.setText(_translate("MainWindow", "Parsing Table", None))
        self.label_2.setText(_translate("MainWindow", "Enter grammar :", None))
        self.label.setText(_translate("MainWindow", "LALR Parser", None))
        self.label_4.setText(_translate("MainWindow", "\'e\' : epsilon", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_About.setTitle(_translate("MainWindow", "&About", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_Exit.setText(_translate("MainWindow", "&Exit", None))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAuthor.setText(_translate("MainWindow", "Author", None))
        
        self.parse.setStyleSheet("background-color: white; border: 2px solid black; color: black;")
        self.displayButton.setStyleSheet("background-color: white; border: 2px solid black; color: black;")
        self.firstButton.setStyleSheet("background-color: white; border: 2px solid black; color: black;")
        self.lr1Button.setStyleSheet("background-color: white; border: 2px solid black; color: black;")
        self.lalrButton.setStyleSheet("background-color: white; border: 2px solid black; color: black;")
        self.parseTableButton.setStyleSheet("background-color: white; border: 2px solid black; color: black;")
        self.label.setStyleSheet("color: black;")
        self.label_2.setStyleSheet("color: black;")
        self.label_3.setStyleSheet("color: black;")
        self.label_4.setStyleSheet("color: black;")
        
        self.label_2.adjustSize()
        self.label_3.adjustSize()
        self.label_4.adjustSize()
        self.epsilonBox.adjustSize()

